baseURL = "https://yigithanbalci.github.io/"
languageCode = "en-us"
title = "Yigithan Kadir Balci"
theme = "hugo-coder"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

# googleAnalytics = "UA-XXXXXX-X"                             # Optional, replace with your Google Analytics ID
[params]
author = "Yigithan Kadir Balci"
description = "Personal Page"
info = "Senior Software Engineer@Accenture"
keywords = "blog,developer,personal,portfolio"
avatarurl = "images/avatar.jpg"
#gravatar = "john.doe@example.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/yigithanbalci/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/yigithanbalci/"
[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/yigithanbalci/"
[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/yigithankadir/"
[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 3
url = "https://www.youtube.com/@yeetkhan"
[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 3
url = "https://medium.com/@yigithanbalci"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "https://medium.com/@yigithanbalci"
# [[menu.main]]
# name = "About"
# weight = 2
# url = "about/"

[caches]
[caches.images]
dir = ':cacheDir/images'
